### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by r34son** [yc-actions/yc-obj-storage-upload#188]
Получаю ошибку при попытке загрузить вложенную директорию
<img width="528" alt="image" src="https://github.com/yc-actions/yc-obj-storage-upload/assets/43549299/74a8b65b-d4c4-4510-97e0-0f9d80c33690">
UPD: нашел такой workaround
```yml
   include: |
      _next/static/chunks/*.js
      _next/static/chunks/app
      _next/static/chunks/pages
      _next/static/css
      _next/static/media
      !(_next)/**/*
```
Но не идеальный, т.к. есть директория с хешем. Кажется нужна доработка в экшене.

Оставлю структуру также, возможно поможет при дебаге
<img width="387" alt="image" src="https://github.com/yc-actions/yc-obj-storage-upload/assets/43549299/91f0ad92-f196-4a8d-b79a-1d1296750a93">

**Comment by nikolaymatrosov** [comment]
Пожалуйста, приложите ссылку на репозиторий, где воспроизводится ошибка.

**Comment by r34son** [comment]
> Пожалуйста, приложите ссылку на репозиторий, где воспроизводится ошибка.

https://github.com/r34son/profile

**Comment by pyatnitsev** [comment]
Подтверждаю, та же проблема.

<img width="956" alt="Screenshot 2024-02-17 at 00 57 36" src="https://github.com/yc-actions/yc-obj-storage-upload/assets/4361764/98ec75f1-7466-4462-a2ca-55a404089ac6">
