### ISSUE TITLE
Добавить возможность очищения бакета перед загрузкой

### ISSUE THREAD

**Issue by D1ver** [yc-actions/yc-obj-storage-upload#352]
Часто требуется очищать бакет перед загрузкой.
Можно было бы добавить в блок with параметр clear: true/false, который бы очищал бакет перед загрузкой, если true.
Пример такой реализации: https://github.getafreenode.com/NekitCorp/yandex-storage-website-action

**Comment by ivantitov-zd** [comment]
@nikolaymatrosov вижу, что фича реализована во второй версии, но при попытке использовать в логе говорится об отсутствии параметра clear. Я что-то делаю не так или проблема реально есть?

![image](https://github.com/yc-actions/yc-obj-storage-upload/assets/28631927/e26becb7-5ff2-4a48-82a0-ed7d1d17a427)
