### ISSUE TITLE
Добавить параметр Cache-Control

### ISSUE THREAD

**Issue by melang982** [yc-actions/yc-obj-storage-upload#456]
Например для картинок и статических файлов часто требуется выставить 'max-age=31536000'

**Comment by nikolaymatrosov** [comment]
Как вы видите конфигурацию этого параметра? Глобально для всех файлов? Или нужна более гибкая конфигурация? Если да, то как? На основе пути или mime-type?

**Comment by melang982** [comment]
На основе маски было бы удобно, чтобы например для *.js и *.css выставлять одно, а для *.svg другое

**Comment by nikolaymatrosov** [comment]
Приведите примеры.

**Comment by melang982** [comment]
Например я заливаю на s3 фронтенд, у меня .js и .css файлы в имени содержат версию: index-DKLXIlNe.js, соответственно их можно кэшировать навсегда: `Cache-Control: public, max-age=31536000, immutable`
А все остальные файлы не содержат в имени версии, их необходимо проверять: `Cache-Control: no-cache` (допустим)

Что-то вроде
`cache-control: |
  "*.js, *.css: public, max-age=31536000, immutable
  *: no-cache"`
